<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>d1030c31-7b26-486e-ba62-ace09f49e48a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-16']/div/div/div[2]/div/div/div[2]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ng-tns-c172-253.ant-btn.ant-btn-primary.ant-btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b18e84da-9c21-47bf-8a0c-c5cb1eb19606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c172-253 ant-btn ant-btn-primary ant-btn-sm</value>
      <webElementGuid>f3064d41-8c14-44fc-a373-06993a5e2894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>88731941-eaf1-41ec-bc94-162d3edb48b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-16&quot;)/div[@class=&quot;ant-popover ng-tns-c172-253 ng-trigger ng-trigger-zoomBigMotion ng-star-inserted null ant-popover-placement-left&quot;]/div[@class=&quot;ant-popover-content ng-tns-c172-253&quot;]/div[@class=&quot;ant-popover-inner ng-tns-c172-253&quot;]/div[@class=&quot;ng-tns-c172-253&quot;]/div[@class=&quot;ant-popover-inner-content ng-tns-c172-253&quot;]/div[@class=&quot;ant-popover-buttons ng-tns-c172-253&quot;]/button[@class=&quot;ng-tns-c172-253 ant-btn ant-btn-primary ant-btn-sm&quot;]</value>
      <webElementGuid>0a332239-8554-425e-8958-a43ed539071f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e409951-f91a-433a-a5a6-929e4a1214aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c172-40 ant-btn ant-btn-primary ant-btn-sm</value>
      <webElementGuid>415eb296-74e4-4e45-86f4-6a7b5a97f41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>1841bac8-dfcc-4f9c-ba64-14661d18af46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-5&quot;)/div[@class=&quot;ant-popover ng-tns-c172-40 ng-trigger ng-trigger-zoomBigMotion ng-star-inserted null ant-popover-placement-left&quot;]/div[@class=&quot;ant-popover-content ng-tns-c172-40&quot;]/div[@class=&quot;ant-popover-inner ng-tns-c172-40&quot;]/div[@class=&quot;ng-tns-c172-40&quot;]/div[@class=&quot;ant-popover-inner-content ng-tns-c172-40&quot;]/div[@class=&quot;ant-popover-buttons ng-tns-c172-40&quot;]/button[@class=&quot;ng-tns-c172-40 ant-btn ant-btn-primary ant-btn-sm&quot;]</value>
      <webElementGuid>fff0d4f3-ebe0-4331-ac1b-d5a8cb3b0116</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-16']/div/div/div[2]/div/div/div[2]/button[2]</value>
      <webElementGuid>af6ed747-ec75-4a52-998a-0497f3277f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>4a063d60-cc2e-4ab5-9477-591fdf0ae868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda yakin akan menghapus data cabang ini?'])[1]/following::button[2]</value>
      <webElementGuid>ae6008c2-7176-4cab-8b5b-4226d9fab850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>ce696cd2-e520-4982-af0f-624290367707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>c02dcf0d-003b-48ba-a3e2-6592afc4b67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-5']/div/div/div[2]/div/div/div[2]/button[2]</value>
      <webElementGuid>531bfd62-e79a-4241-ae8c-6e1ebb308ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda yakin akan menghapus role ini?'])[1]/following::button[2]</value>
      <webElementGuid>df6d64fb-20d1-4f2a-b770-3108e6857616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/button[2]</value>
      <webElementGuid>ca342765-98bf-4947-89a5-406abd1a767d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
