<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>b2750b10-6c96-4461-b55b-8662b22860c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-14']/div/div/div[2]/div/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ng-tns-c172-251.ant-btn.ant-btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>733fa176-0cfc-42f9-a910-530af0082bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c172-251 ant-btn ant-btn-sm</value>
      <webElementGuid>bdf35226-2359-489f-856f-32e1f1ce84f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>74bb98f5-e528-4cea-b8ae-bcfebddc9de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-14&quot;)/div[@class=&quot;ant-popover ng-tns-c172-251 ng-trigger ng-trigger-zoomBigMotion ng-star-inserted null ant-popover-placement-left&quot;]/div[@class=&quot;ant-popover-content ng-tns-c172-251&quot;]/div[@class=&quot;ant-popover-inner ng-tns-c172-251&quot;]/div[@class=&quot;ng-tns-c172-251&quot;]/div[@class=&quot;ant-popover-inner-content ng-tns-c172-251&quot;]/div[@class=&quot;ant-popover-buttons ng-tns-c172-251&quot;]/button[@class=&quot;ng-tns-c172-251 ant-btn ant-btn-sm&quot;]</value>
      <webElementGuid>ced5c422-844e-440a-889a-fc90d55bfbc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>568f71b0-e1a8-4ba3-8c48-1f95988d185a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c172-40 ant-btn ant-btn-sm</value>
      <webElementGuid>f7c02b9e-ab1f-4cd0-bf0e-b6955c8257f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>2199b5ec-6d8e-4cdd-9b72-c2e1e5a7aac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-5&quot;)/div[@class=&quot;ant-popover ng-tns-c172-40 ng-trigger ng-trigger-zoomBigMotion ng-star-inserted null ant-popover-placement-left&quot;]/div[@class=&quot;ant-popover-content ng-tns-c172-40&quot;]/div[@class=&quot;ant-popover-inner ng-tns-c172-40&quot;]/div[@class=&quot;ng-tns-c172-40&quot;]/div[@class=&quot;ant-popover-inner-content ng-tns-c172-40&quot;]/div[@class=&quot;ant-popover-buttons ng-tns-c172-40&quot;]/button[@class=&quot;ng-tns-c172-40 ant-btn ant-btn-sm&quot;]</value>
      <webElementGuid>73538eea-1c66-422e-b802-d41534ec8434</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-14']/div/div/div[2]/div/div/div[2]/button</value>
      <webElementGuid>89e660dc-e895-4de0-94a6-18624f2ae44b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda yakin akan menghapus data cabang ini?'])[1]/following::button[1]</value>
      <webElementGuid>2ba09009-336a-4be3-a24f-5a0f17a9c4cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manajemen Role'])[2]/following::button[1]</value>
      <webElementGuid>47f75f01-2a1b-40af-a8e5-1b17fc44ee91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::button[1]</value>
      <webElementGuid>9d100047-db5c-4038-b78c-c90fd5ffe1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/button</value>
      <webElementGuid>559ac8fe-04d7-4df0-bac8-8680092a5ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>931e8f77-e91d-446c-aad0-f7adab031eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-5']/div/div/div[2]/div/div/div[2]/button</value>
      <webElementGuid>80ef1c83-1dba-467d-a6e4-b2583da73e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda yakin akan menghapus role ini?'])[1]/following::button[1]</value>
      <webElementGuid>ffa3e53c-64ea-4f76-bac8-4196c5b9960f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permission'])[1]/following::button[1]</value>
      <webElementGuid>230de93d-3169-4036-b0b9-8c4b4af09dc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
